-- Immutable monthly Annex E-1 workbook identity and content-addressed artifact metadata.

CREATE TABLE IF NOT EXISTS pos.annex_e1_workbooks (
    annex_e1_workbook_id uuid NOT NULL,
    annex_e_reference text NOT NULL,
    operation_key text NOT NULL,
    site_pos_server_id uuid NOT NULL,
    fiscal_identity_id uuid NOT NULL,
    currency_code char(3) NOT NULL,
    calendar_year integer NOT NULL,
    calendar_month integer NOT NULL,
    profile_ref text NOT NULL,
    calculation_profile_ref text NOT NULL,
    calculation_profile_sha256 char(64) NOT NULL,
    template_sha256 char(64) NOT NULL,
    renderer_version text NOT NULL,
    revision integer NOT NULL,
    semantic_hash_version text NOT NULL,
    semantic_hash char(64) NOT NULL,
    artifact_sha256 char(64) NOT NULL,
    artifact_byte_length bigint NOT NULL,
    artifact_storage_key text NOT NULL,
    mime_type text NOT NULL,
    file_name text NOT NULL,
    taxpayer_name text NOT NULL,
    taxpayer_address text NOT NULL,
    tin text NOT NULL,
    pos_serial_number text NOT NULL,
    machine_identification_number text NOT NULL,
    pos_terminal_number text NOT NULL,
    software_name text NOT NULL,
    software_version text NOT NULL,
    release_number text NOT NULL,
    release_date text NOT NULL,
    workbook_status_code_id uuid NOT NULL,
    supersedes_workbook_id uuid NULL,
    correction_reason_code_id uuid NULL,
    correction_approval_reference text NULL,
    generated_at timestamptz NOT NULL,
    committed_at timestamptz NOT NULL,
    generated_by_ref text NOT NULL,
    service_identity_ref text NOT NULL,
    correlation_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_annex_e1_workbooks PRIMARY KEY (annex_e1_workbook_id),
    CONSTRAINT fk_annex_e1_workbooks__site FOREIGN KEY (site_pos_server_id) REFERENCES pos.site_pos_servers (site_pos_server_id),
    CONSTRAINT fk_annex_e1_workbooks__identity FOREIGN KEY (fiscal_identity_id) REFERENCES pos.fiscal_identities (fiscal_identity_id),
    CONSTRAINT fk_annex_e1_workbooks__status FOREIGN KEY (workbook_status_code_id) REFERENCES pos.controlled_codes (controlled_code_id),
    CONSTRAINT fk_annex_e1_workbooks__supersedes FOREIGN KEY (supersedes_workbook_id) REFERENCES pos.annex_e1_workbooks (annex_e1_workbook_id),
    CONSTRAINT fk_annex_e1_workbooks__correction_reason FOREIGN KEY (correction_reason_code_id) REFERENCES pos.controlled_codes (controlled_code_id),
    CONSTRAINT uq_annex_e1_workbooks__reference UNIQUE (annex_e_reference),
    CONSTRAINT uq_annex_e1_workbooks__scope_operation UNIQUE (site_pos_server_id, operation_key),
    CONSTRAINT uq_annex_e1_workbooks__scope_revision UNIQUE (site_pos_server_id, fiscal_identity_id, currency_code, calendar_year, calendar_month, profile_ref, revision),
    CONSTRAINT uq_annex_e1_workbooks__supersedes UNIQUE (supersedes_workbook_id),
    CONSTRAINT ck_annex_e1_workbooks__profile CHECK (profile_ref='pos-server-bir-annex-e1-rmo24-2023:v1' AND calculation_profile_ref='pos-server-annex-e1-accounting-calculation:v1' AND calculation_profile_sha256='36bbba7f014f5713955d50fe2fdab63f0cb6e80aab77713fe5fef45fbe7c1a4f'),
    CONSTRAINT ck_annex_e1_workbooks__template CHECK (template_sha256='7e46f34ae8779b303baa903f01bde794a519732de881d78109f79047d5a44197'),
    CONSTRAINT ck_annex_e1_workbooks__status CHECK (workbook_status_code_id='f5c2b69b-7d60-5fcb-a532-728d179de646'),
    CONSTRAINT ck_annex_e1_workbooks__correction_reason CHECK (correction_reason_code_id IS NULL OR correction_reason_code_id IN ('bca6e858-3c1a-5641-afbb-35cfba91caa2','3324411d-f392-501c-8b97-924fd19e5f7c')),
    CONSTRAINT ck_annex_e1_workbooks__scope CHECK (currency_code='PHP' AND calendar_year BETWEEN 2000 AND 9999 AND calendar_month BETWEEN 1 AND 12 AND revision > 0),
    CONSTRAINT ck_annex_e1_workbooks__hashes CHECK (semantic_hash ~ '^[0-9a-f]{64}$' AND artifact_sha256 ~ '^[0-9a-f]{64}$' AND artifact_byte_length > 0),
    CONSTRAINT ck_annex_e1_workbooks__artifact CHECK (char_length(btrim(artifact_storage_key)) > 0 AND mime_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' AND file_name ~ '^ANNEX-E1_[A-Za-z0-9._-]+\.xlsx$'),
    CONSTRAINT ck_annex_e1_workbooks__correction CHECK ((supersedes_workbook_id IS NULL AND correction_reason_code_id IS NULL AND correction_approval_reference IS NULL) OR (supersedes_workbook_id IS NOT NULL AND correction_reason_code_id IS NOT NULL AND char_length(btrim(correction_approval_reference)) > 0)),
    CONSTRAINT ck_annex_e1_workbooks__timestamps CHECK (committed_at >= generated_at)
);

CREATE INDEX IF NOT EXISTS ix_annex_e1_workbooks__scope_month ON pos.annex_e1_workbooks (site_pos_server_id, fiscal_identity_id, currency_code, calendar_year, calendar_month, revision DESC);
CREATE OR REPLACE TRIGGER trg_annex_e1_workbooks_immutable BEFORE UPDATE OR DELETE ON pos.annex_e1_workbooks FOR EACH ROW EXECUTE FUNCTION pos.reject_fiscal_reporting_snapshot_mutation();

