-- Reprint output evidence. Canonical rows are immutable and contain references
-- only; generated output bytes are not stored in PostgreSQL.

CREATE TABLE IF NOT EXISTS pos.reprint_output_refs (
    reprint_output_ref_id uuid NOT NULL,
    reprint_request_id uuid NOT NULL,
    output_type_code_id uuid NOT NULL,
    output_ref text NULL,
    reprint_label_applied boolean NOT NULL DEFAULT true,
    reprinted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    printed_by_ref text NULL,
    channel_terminal_id uuid NULL,
    output_context jsonb NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_reprint_output_refs PRIMARY KEY (reprint_output_ref_id),
    CONSTRAINT fk_reprint_output_refs__request FOREIGN KEY (reprint_request_id)
        REFERENCES pos.reprint_requests (reprint_request_id),
    CONSTRAINT fk_reprint_output_refs__output_type FOREIGN KEY (output_type_code_id)
        REFERENCES pos.controlled_codes (controlled_code_id),
    CONSTRAINT fk_reprint_output_refs__channel FOREIGN KEY (channel_terminal_id)
        REFERENCES pos.channel_terminals (channel_terminal_id),
    CONSTRAINT ck_reprint_output_refs__output_ref CHECK (
        output_ref IS NULL OR char_length(btrim(output_ref)) > 0
    ),
    CONSTRAINT ck_reprint_output_refs__printed_by_ref CHECK (
        printed_by_ref IS NULL OR char_length(btrim(printed_by_ref)) > 0
    ),
    CONSTRAINT ck_reprint_output_refs__context_object CHECK (
        output_context IS NULL OR jsonb_typeof(output_context) = 'object'
    )
);

ALTER TABLE pos.reprint_output_refs
    ADD COLUMN IF NOT EXISTS output_reference text NULL,
    ADD COLUMN IF NOT EXISTS is_canonical boolean NOT NULL DEFAULT false;

ALTER TABLE pos.reprint_output_refs
    DROP CONSTRAINT IF EXISTS ck_reprint_output_refs__canonical_required,
    DROP CONSTRAINT IF EXISTS ck_reprint_output_refs__type_family,
    DROP CONSTRAINT IF EXISTS ck_reprint_output_refs__canonical_privacy;

ALTER TABLE pos.reprint_output_refs
    ADD CONSTRAINT ck_reprint_output_refs__canonical_required CHECK (
        NOT is_canonical OR (
            output_reference IS NOT NULL AND btrim(output_reference) <> ''
            AND output_ref = output_reference
            AND reprint_label_applied
            AND printed_by_ref IS NOT NULL AND btrim(printed_by_ref) <> ''
        )
    ),
    ADD CONSTRAINT ck_reprint_output_refs__type_family CHECK (
        NOT is_canonical OR output_type_code_id = 'cc4ac16f-401f-5b8e-b817-464fc1e4ceb2'
    ),
    ADD CONSTRAINT ck_reprint_output_refs__canonical_privacy CHECK (
        NOT is_canonical OR output_context IS NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_reprint_output_refs__request
    ON pos.reprint_output_refs (reprint_request_id) WHERE is_canonical;
CREATE UNIQUE INDEX IF NOT EXISTS ux_reprint_output_refs__reference
    ON pos.reprint_output_refs (output_reference) WHERE is_canonical;

CREATE OR REPLACE TRIGGER trg_reprint_output_refs_immutable
BEFORE UPDATE OR DELETE ON pos.reprint_output_refs
FOR EACH ROW EXECUTE FUNCTION pos.reject_canonical_reprint_mutation();

COMMENT ON TABLE pos.reprint_output_refs IS
    'Immutable canonical reprint output evidence plus retained non-canonical legacy posture. Stores references only, never generated bytes.';
COMMENT ON COLUMN pos.reprint_output_refs.reprint_label_applied IS
    'Canonical reprint output evidence requires the reprint label posture.';
COMMENT ON COLUMN pos.reprint_output_refs.output_ref IS
    'Optional output reference only; generated PDF, print, or binary output is not stored here.';
COMMENT ON COLUMN pos.reprint_output_refs.output_context IS
    'Legacy posture metadata only; canonical output evidence prohibits generic context.';
