namespace ExitPass.PosServer.Runtime.FiscalDocuments;

public static class DigitalSalesInvoiceTemplateContract
{
    public const string TemplateContractVersion = "digital-sales-invoice-json-v1";
    public const string FiscalTemplateFamily = "PH_DIGITAL_SALES_INVOICE";
    public const string RenderFormat = "application/json";

    private static readonly string[] DisplayResponsibilities =
    [
        "POS Server provides structured fiscal data only.",
        "UI, print, PDF, and presentation renderers decide layout.",
        "Placeholder text is not final BIR template text."
    ];

    private static readonly DigitalSalesInvoiceTemplateContractPostureModel[] SupportedPostures =
    [
        new("required", "Expected in the JSON contract for normal rendering."),
        new("optional", "Available when the fiscal document read model has the value."),
        new("not_available", "Declared unavailable in this contract version or current source state."),
        new("placeholder", "Safe placeholder metadata or text only."),
        new("deferred", "Intentionally not generated by this contract slice.")
    ];

    private static readonly DigitalSalesInvoiceTemplateContractSectionModel[] Sections =
    [
        Section("header", "required", "Receipt header and contract metadata."),
        Section("sales_invoice_header_snapshot", "optional", "Immutable Sales Invoice statutory and site header snapshot."),
        Section("seller_site_pos_identity", "required", "Site POS Server, channel terminal, and fiscal identity references."),
        Section("document_identity", "required", "Fiscal document id, type, status, and business day."),
        Section("fiscal_numbering", "required", "Fiscal number state and assigned numbering evidence when available."),
        Section("parking_payment_references", "optional", "Central PMS parking, payment, finality, and vendor acknowledgement references."),
        Section("line_items", "required", "Fiscal line item facts."),
        Section("discounts", "optional", "Discount and privilege reference facts."),
        Section("taxes", "optional", "Tax detail facts."),
        Section("tenders", "required", "Tender allocation facts."),
        Section("totals", "required", "Fiscal total facts."),
        Section("audit_hash_status", "required", "Semantic hash, status, and audit timestamps."),
        Section("footer_disclaimers", "placeholder", "Non-final footer/disclaimer placeholders."),
        Section("deferred_placeholders", "deferred", "Future QR, PDF, HTML, statutory template, and URL artifacts.")
    ];

    private static readonly DigitalSalesInvoiceTemplateContractFieldModel[] Fields =
    [
        Field("header.templateContractVersion", "required"),
        Field("header.fiscalTemplateFamily", "required"),
        Field("header.renderFormat", "required"),
        Field("salesInvoiceHeaderSnapshot.registeredBusinessName", "optional"),
        Field("salesInvoiceHeaderSnapshot.registeredBusinessAddress", "optional"),
        Field("salesInvoiceHeaderSnapshot.tin", "optional"),
        Field("salesInvoiceHeaderSnapshot.posSerialNumber", "optional"),
        Field("salesInvoiceHeaderSnapshot.machineIdentificationNumber", "optional"),
        Field("salesInvoiceHeaderSnapshot.parkingLocationDisplay", "optional"),
        Field("salesInvoiceHeaderSnapshot.terminalId", "optional"),
        Field("salesInvoiceHeaderSnapshot.birAccreditationNumber", "optional"),
        Field("salesInvoiceHeaderSnapshot.birAccreditationIssuedDate", "optional"),
        Field("salesInvoiceHeaderSnapshot.birAccreditationValidUntil", "optional"),
        Field("salesInvoiceHeaderSnapshot.ptuNumber", "optional"),
        Field("salesInvoiceHeaderSnapshot.ptuIssuedDate", "optional"),
        Field("salesInvoiceHeaderSnapshot.salesInvoiceLegalStatement", "optional"),
        Field("salesInvoiceHeaderSnapshot.customerServiceFooter", "optional"),
        Field("salesInvoiceHeaderSnapshot.profileVersion", "optional"),
        Field("salesInvoiceHeaderSnapshot.templateVersion", "optional"),
        Field("salesInvoiceHeaderSnapshot.presentationVersion", "optional"),
        Field("sellerSitePosIdentity.sitePosServerId", "required"),
        Field("sellerSitePosIdentity.channelTerminalId", "optional"),
        Field("sellerSitePosIdentity.fiscalIdentityId", "optional"),
        Field("documentIdentity.fiscalDocumentId", "required"),
        Field("documentIdentity.fiscalDocumentTypeCodeId", "required"),
        Field("documentIdentity.fiscalDocumentTypeCodeKey", "optional"),
        Field("documentIdentity.fiscalDocumentStatusCodeId", "required"),
        Field("documentIdentity.fiscalDocumentStatusCodeKey", "optional"),
        Field("documentIdentity.businessDayDate", "optional"),
        Field("documentIdentity.recordedAt", "required"),
        Field("documentIdentity.voidStatus", "optional"),
        Field("documentIdentity.voidReasonCode", "optional"),
        Field("documentIdentity.voidedAt", "optional"),
        Field("fiscalNumbering.fiscalNumberAssignmentState", "required"),
        Field("fiscalNumbering.fiscalDocumentNumber", "optional"),
        Field("fiscalNumbering.fiscalSeries", "optional"),
        Field("fiscalNumbering.fiscalNumberPrefixText", "optional"),
        Field("fiscalNumbering.fiscalNumberSuffixText", "optional"),
        Field("fiscalNumbering.fiscalNumberAssignedAt", "optional"),
        Field("fiscalNumbering.fiscalNumberAssignedByRef", "optional"),
        Field("parkingPaymentReferences.centralPmsParkingSessionRef", "optional"),
        Field("parkingPaymentReferences.centralPmsPaymentAttemptRef", "optional"),
        Field("parkingPaymentReferences.centralPmsPaymentConfirmationRef", "optional"),
        Field("parkingPaymentReferences.paymentFinalityRef", "optional"),
        Field("parkingPaymentReferences.vendorAckRef", "optional"),
        Field("lineItems", "required"),
        Field("discounts", "optional"),
        Field("taxes", "optional"),
        Field("tenders", "required"),
        Field("tenders.tenderTypeCodeKey", "optional"),
        Field("totals", "required"),
        Field("auditHashStatus.semanticRequestHash", "optional"),
        Field("auditHashStatus.semanticRequestHashVersion", "optional"),
        Field("auditHashStatus.semanticRequestHashStatus", "optional"),
        Field("footerDisclaimers", "placeholder"),
        Field("deferredPlaceholders.qrCode", "deferred"),
        Field("deferredPlaceholders.pdfDocument", "deferred"),
        Field("deferredPlaceholders.htmlDocument", "deferred"),
        Field("deferredPlaceholders.digitalSalesInvoiceUrl", "deferred"),
        Field("deferredPlaceholders.finalBirTemplateText", "deferred")
    ];

    private static readonly DigitalSalesInvoiceTemplateContractPlaceholderModel[] DeferredPlaceholders =
    [
        new("qrCode", "deferred", "QR code rendering is not part of this JSON contract slice."),
        new("pdfDocument", "deferred", "PDF generation is not part of this JSON contract slice."),
        new("htmlDocument", "deferred", "HTML rendering is not part of this JSON contract slice."),
        new("digitalSalesInvoiceUrl", "deferred", "Digital SI URL storage/access is not part of this JSON contract slice."),
        new("finalBirTemplateText", "deferred", "Final statutory template text requires separate compliance approval.")
    ];

    public static DigitalSalesInvoiceTemplateContractModel Create() =>
        new(
            TemplateContractVersion,
            FiscalTemplateFamily,
            RenderFormat,
            "structured_fiscal_data_only",
            DisplayResponsibilities,
            SupportedPostures,
            Sections,
            Fields,
            DeferredPlaceholders);

    private static DigitalSalesInvoiceTemplateContractSectionModel Section(
        string name,
        string posture,
        string description) =>
        new(name, posture, description);

    private static DigitalSalesInvoiceTemplateContractFieldModel Field(string path, string posture) =>
        new(path, posture);
}

public sealed record DigitalSalesInvoiceTemplateContractModel(
    string TemplateContractVersion,
    string FiscalTemplateFamily,
    string RenderFormat,
    string DisplayResponsibility,
    IReadOnlyList<string> DisplayResponsibilityNotes,
    IReadOnlyList<DigitalSalesInvoiceTemplateContractPostureModel> SupportedPostures,
    IReadOnlyList<DigitalSalesInvoiceTemplateContractSectionModel> Sections,
    IReadOnlyList<DigitalSalesInvoiceTemplateContractFieldModel> Fields,
    IReadOnlyList<DigitalSalesInvoiceTemplateContractPlaceholderModel> DeferredPlaceholders);

public sealed record DigitalSalesInvoiceTemplateContractPostureModel(
    string Name,
    string Description);

public sealed record DigitalSalesInvoiceTemplateContractSectionModel(
    string Name,
    string Posture,
    string Description);

public sealed record DigitalSalesInvoiceTemplateContractFieldModel(
    string Path,
    string Posture);

public sealed record DigitalSalesInvoiceTemplateContractPlaceholderModel(
    string Name,
    string Posture,
    string Description);
