namespace ExitPass.PosServer.Runtime.FiscalDocuments;

public sealed record FiscalDocumentDraft(
    Guid FiscalDocumentId,
    Guid SitePosServerId,
    Guid? ChannelTerminalId,
    Guid FiscalDocumentTypeCodeId,
    Guid FiscalDocumentStatusCodeId,
    string SitePosServerRef,
    string FiscalDocumentTypeCodeKey,
    string PayableBasisRef,
    string UpstreamFinalityRef,
    string CurrencyCode,
    long PayableAmountMinorUnits,
    DateOnly? BusinessDayDate,
    string? CentralPmsParkingSessionRef,
    string? CentralPmsPaymentAttemptRef,
    string? CentralPmsPaymentConfirmationRef,
    string? PaymentFinalityRef,
    string? VendorAckRef,
    IReadOnlyList<FiscalDocumentLinkInput> DocumentLinks,
    IReadOnlyList<FiscalDocumentLineInput> DocumentLines,
    IReadOnlyList<FiscalTenderInput> Tenders,
    IReadOnlyList<FiscalTaxDetailInput> TaxDetails,
    IReadOnlyList<FiscalDiscountPrivilegeDetailInput> DiscountPrivilegeDetails,
    IReadOnlyList<FiscalTotalInput> Totals,
    IReadOnlyList<FiscalDiscountReferenceInput> DiscountReferences,
    Guid? ResolvedFiscalIdentityId = null,
    Guid? ResolvedFiscalSequencePolicyId = null,
    long? FiscalSequenceValue = null,
    string? FiscalDocumentNumber = null,
    string? FiscalSeries = null,
    string? FiscalNumberPrefixText = null,
    string? FiscalNumberSuffixText = null,
    DateTimeOffset? FiscalNumberAssignedAt = null,
    string? FiscalNumberAssignedByRef = null);
