namespace ExitPass.PosServer.Runtime.FiscalDocuments;

public sealed record FiscalDocumentCreationCommand(
    string SitePosServerRef,
    string FiscalDocumentTypeCodeKey,
    FiscalizationPayableBasisInput? PayableBasis,
    Guid? SitePosServerId = null,
    Guid? SiteId = null,
    Guid? ChannelTerminalId = null,
    string? RuntimeTerminalRef = null,
    Guid? FiscalDocumentTypeCodeId = null,
    Guid? FiscalDocumentStatusCodeId = null,
    DateOnly? BusinessDayDate = null,
    string? CentralPmsParkingSessionRef = null,
    string? CentralPmsPaymentAttemptRef = null,
    string? CentralPmsPaymentConfirmationRef = null,
    string? PaymentFinalityRef = null,
    string? VendorAckRef = null,
    IReadOnlyList<FiscalDocumentLinkInput>? DocumentLinks = null,
    IReadOnlyList<FiscalDocumentLineInput>? DocumentLines = null,
    IReadOnlyList<FiscalTenderInput>? Tenders = null,
    IReadOnlyList<FiscalTaxDetailInput>? TaxDetails = null,
    IReadOnlyList<FiscalDiscountPrivilegeDetailInput>? DiscountPrivilegeDetails = null,
    IReadOnlyList<FiscalTotalInput>? Totals = null,
    IReadOnlyDictionary<string, string>? ReferenceContext = null,
    AppliedStatutoryFiscalFactsInput? AppliedStatutoryFiscalFacts = null);

public sealed record AppliedStatutoryFiscalFactsInput(
    Guid? StatutoryDiscountDecisionCommandId,
    Guid? StatutoryRequestReference,
    Guid? StatutoryPayableBasisApplicationCommandId,
    Guid? StatutoryValidationId,
    Guid? ParkingSessionId,
    Guid? SiteId,
    Guid? SiteGroupId,
    string? EntitlementType,
    string? BenefitClassification,
    AppliedStatutoryPolicyReferenceInput? PolicyReference,
    Guid? OriginalTariffSnapshotId,
    Guid? AppliedTariffSnapshotId,
    long? OriginalAmountMinorUnits,
    long? VatExclusiveBasisAmountMinorUnits,
    long? VatAmountMinorUnits,
    string? VatTreatment,
    long? StatutoryDiscountAmountMinorUnits,
    long? FinalPayableAmountMinorUnits,
    string? Currency,
    DateTimeOffset? AppliedAt,
    string? SourcePaymentChannel,
    Guid? TerminalCashTenderId = null,
    IReadOnlyList<string>? UnknownFieldNames = null);

public sealed record AppliedStatutoryPolicyReferenceInput(
    string? ResolutionBasis,
    Guid? AppliedPolicyReferenceId = null,
    string? PolicyCode = null,
    Guid? PolicyVersionId = null,
    string? NationalLawReference = null,
    string? OrdinanceReference = null,
    IReadOnlyList<string>? UnknownFieldNames = null);
